services:
  backend:
    build: .
    entrypoint: /app/entrypoint.sh
    container_name: LM_backend
    ports:
      - "8000:8000"
    volumes:
      - ./alembic:/app/alembic
    env_file:
      - environment/.env
      - environment/.env.postgresql
      - environment/.env.redis
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres_db:
    image: postgres:17
    container_name: LM_postgres_db
    ports:
      - "5432:5432"
    env_file:
      - environment/.env.postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5

  redis:
    image: redis:8
    container_name: LM_redis
    ports:
      - "6379:6379"
    env_file:
      - environment/.env.redis
    volumes:
      - redis_data:/data
      - ./redis-setup.sh:/usr/local/bin/redis-setup.sh
    command: sh /usr/local/bin/redis-setup.sh
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5

volumes:
  postgres_data:
  redis_data:
